### ISSUE TITLE
It's not working with angular 4

### ISSUE THREAD

**Issue by robinmaple** [tycomo/ngx-ssrs-reportviewer#1]
Appreciated your effort in developing this, and I think there is solid need for this. But it didn't work when I  tried it with angular 4. No error was prompted, but it created a really weird layer. 

![image](https://user-images.githubusercontent.com/7815640/32864731-868369fc-ca1d-11e7-873c-84838ad5214a.png)

**Comment by tycomo** [comment]
Hi @robinmaple , other obligations have kept me from keeping this up to date.

I have a branch I am working on that will update it to the latest version of Angular that should be out this weekend.

Thanks for understanding.
