### ISSUE TITLE
SSRS Report(.rdl) with Angular reportviewer

### ISSUE THREAD

**Issue by egMani91** [tycomo/ngx-ssrs-reportviewer#10]
Hi, I am a beginner in Angular. I facing issue while loading SSRS report (.rdl file) in ngx-ssrs-reportviewer.  In app.component.ts file I have passed my API  " reportServer: string = 'http://localhost:29919/api/MonthwisePayment';"  and mentioned report path "reportUrl: string = 'Reports/DemoApi.rdl'; " Here I have attached .rdl file in my API file under "Reports" folder .  I was able to see only my API data in Reportviewer  which is in json format. But I want to load my Report (.rdl) file in viewer instead of API data.  Is there any solution ?

**Comment by tycomo** [comment]
Right now I do not have support for reading the .rdl.  Currently it has to be published to the report server for the web app to reach the URL to render it inside the app.

This will be something I investigate as an enhancement.
