### ISSUE TITLE
ngx-ssrs-reportviewer  Can't resolve '@angular/elements'

### ISSUE THREAD

**Issue by Touqeer345** [tycomo/ngx-ssrs-reportviewer#12]
Hi i face this issue 
ERROR in ./node_modules/ngx-ssrs-reportviewer/fesm5/ngx-ssrs-reportviewer.js
Module not found: Error: Can't resolve '@angular/elements' in 'D:\Projects\GREAT-MVP\Great.Web\ClientApp\node_modules\ngx-ssrs-reportviewer\fesm5'

please help me.

**Comment by cristinatorress** [comment]
So do I, I have the same issue

---------------------------------------
Angular CLI: 1.7.4
Node: 9.5.0
OS: win32 x64
Angular: 5.2.11

@angular/cli: 1.7.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0

**Comment by trongnguyen1210** [comment]
> Hi i face this issue
> ERROR in ./node_modules/ngx-ssrs-reportviewer/fesm5/ngx-ssrs-reportviewer.js
> Module not found: Error: Can't resolve '@angular/elements' in 'D:\Projects\GREAT-MVP\Great.Web\ClientApp\node_modules\ngx-ssrs-reportviewer\fesm5'
> 
> please help me.

You install package:
        [npm i @angular/elements --save]
        [npm i @webcomponents/custom-elements --save]
		- referencing it in the angular.json
			"scripts": [
  					"node_modules/@webcomponents/custom-elements/src/native-shim.js"
				]
...

**Comment by gtmtech-pro** [comment]
I am also facing same issue but after installing two plugins as below then my problem has been resolved and now I can see SSRS report in angular 8. 
1) npm i @angular/elements --save
2) npm i @webcomponents/custom-elements --save

**Comment by gtmtech-pro** [comment]
> > Hi i face this issue
> > ERROR in ./node_modules/ngx-ssrs-reportviewer/fesm5/ngx-ssrs-reportviewer.js
> > Module not found: Error: Can't resolve '@angular/elements' in 'D:\Projects\GREAT-MVP\Great.Web\ClientApp\node_modules\ngx-ssrs-reportviewer\fesm5'
> > please help me.
> 
> You install package:
> [npm i @angular/elements --save]
> [npm i @webcomponents/custom-elements --save]
> - referencing it in the angular.json
> "scripts": [
> "node_modules/@webcomponents/custom-elements/src/native-shim.js"
> ]
> ...

Thanks you very much.  After installing plugins, my SSRS problem resolved

**Comment by tycomo** [comment]
Closing issue, with latest version I removed the dependency on elements and custom-elements.
