### ISSUE TITLE
Problem angular 7 

### ISSUE THREAD

**Issue by gfernandez87** [tycomo/ngx-ssrs-reportviewer#15]
Dear I am trying to use it in Angular 7 and it does not recognize the component. This is the error:

Error: Template parse errors:
Can't bind to 'reportserver' since it isn't a known property of 'ssrs-reportviewer'

**Comment by shanegilbert** [comment]
I had this error when I had not correctly setup the following in the module:

schemas: [CUSTOM_ELEMENTS_SCHEMA],

**Comment by tycomo** [comment]
Removed need for custom elements with latest version. Closing issue.
