### ISSUE TITLE
Need to pass report server crendential

### ISSUE THREAD

**Issue by nishant261989** [tycomo/ngx-ssrs-reportviewer#16]
Hi,

Could you let me know how I can pass report server credential while using ngx-ssrs-reportviewer.

I am able to render report on my browser but however I need to paas report server credential everytime. Could it be there anyway I can paas it from code.

Thanks in advance.

Thanks,
Nishant Jain

**Comment by patilkunal50** [comment]
@nishant261989 Did you find any solution to your problem?  I am stuck in same issue.

**Comment by praveenpenmetsa** [comment]
@nishant261989  or @patilkunal50 Any luck on this? I would like to pass report server credentials..Right now it is working fine as I have access.

**Comment by AhmedGaberAhmed** [comment]
Did you find any solution to your problem? I am stuck in same issue.

**Comment by tycomo** [comment]
duplicate #14 

Will work on a solution for credentials and better documentation on how to resolve authentication related issues.

**Comment by AhmedGaberAhmed** [comment]
u find any solution to resolve authentication related issues.
