### ISSUE TITLE
Reports are not loading when it is palced inside the ng template in Angualr 7.0.7 

### ISSUE THREAD

**Issue by rekhasc1** [tycomo/ngx-ssrs-reportviewer#18]
Hi I am using the ssrs report viewer inside ng template , and respective reports are not loading inside ng template , it i remove ng template it is working.. 

<ng-template>
            <div class="container">
              <div class="row">
                <div class="col-md-12">
                  <div class="card mb-12 shadow-sm">
                    <div class="card-body">
<ssrs-reportviewer [reportserver]="reportServer"
                   [reporturl]="reportUrl"
                   [showparameters]="showParameters"
                   [parameters]="parameters"
                   [language]="language"
                   [width]="width"
                   [height]="height"
                   [toolbar]="toolbar">
</ssrs-reportviewer>
                    </div>
                  </div>
                </div>
              </div>
            </div>
</ng-template>

**Comment by tycomo** [comment]
Was tested using ngIf and ngFor with latest version and it seems to be working okay.  Marking as resolved.
