### ISSUE TITLE
It's not installing

### ISSUE THREAD

**Issue by YashwantRathoreAmicus** [tycomo/ngx-ssrs-reportviewer#2]
Hello,

I have tried to install this package using command "**npm install ngx-ssrs-reportviewer --save**" and It hanging during installation.

Please find below screenshot:

![image](https://user-images.githubusercontent.com/31760632/33884613-5ec16802-df66-11e7-84c3-65700ff64e2b.png)

**Comment by tycomo** [comment]
Hi @YashwantRathoreAmicus , other obligations have kept me from keeping this up to date.

I have a branch I am working on that will update it to the latest version of Angular that should be out this weekend.

Thanks for understanding.
