### ISSUE TITLE
Can't display on Internet Explorer

### ISSUE THREAD

**Issue by Danyx1980** [tycomo/ngx-ssrs-reportviewer#20]
Following up on [this issue](https://github.com/tycomo/ngx-ssrs-reportviewer/issues/12) I saw myself adding @angular/elements to my project, which worked great, except on Internet Explorer, where custom elements don't seem to be supported.

Even after trying out multiple polyfills and such I'm unable to load the report, is there no alternative for this? 

`'customElements' is not defined`
`angular unable to get property 'defineProperties' of null or undefined`

**Comment by hmukundappa** [comment]
Facing same issue here, any update on the fix please?

**Comment by karthiktanj** [comment]
Could you please provide the solution to show the SSRS in Internet Explorer

**Comment by hmukundappa** [comment]
> Could you please provide the solution to show the SSRS in Internet Explorer

I installed all the recommended imports in the polyfill.ts and also in the tsconfig changed the lib to es2018

"lib": [
      "es2018",
      "dom"
    ]
Link helped me, https://medium.com/better-programming/how-to-fix-your-angular-app-when-its-not-working-in-ie11-eb24cb6d9920, it works fine for me now on IE as well.

**Comment by karthiktanj** [comment]
> > Could you please provide the solution to show the SSRS in Internet Explorer
> 
> I installed all the recommended imports in the polyfill.ts and also in the tsconfig changed the lib to es2018
> 
> "lib": [
> "es2018",
> "dom"
> ]
> Link helped me, https://medium.com/better-programming/how-to-fix-your-angular-app-when-its-not-working-in-ie11-eb24cb6d9920, it works fine for me now on IE as well.

Is the ngx-ssrs-reportviewer is working in the Internet Explorer ? . It is not working for me

**Comment by hmukundappa** [comment]
> > > Could you please provide the solution to show the SSRS in Internet Explorer
> > 
> > 
> > I installed all the recommended imports in the polyfill.ts and also in the tsconfig changed the lib to es2018
> > "lib": [
> > "es2018",
> > "dom"
> > ]
> > Link helped me, https://medium.com/better-programming/how-to-fix-your-angular-app-when-its-not-working-in-ie11-eb24cb6d9920, it works fine for me now on IE as well.
> 
> Is the ngx-ssrs-reportviewer is working in the Internet Explorer ? . It is not working for me

Yes it works for me fine on IE11.

**Comment by karthiktanj** [comment]
> > > > Could you please provide the solution to show the SSRS in Internet Explorer
> > > 
> > > 
> > > I installed all the recommended imports in the polyfill.ts and also in the tsconfig changed the lib to es2018
> > > "lib": [
> > > "es2018",
> > > "dom"
> > > ]
> > > Link helped me, https://medium.com/better-programming/how-to-fix-your-angular-app-when-its-not-working-in-ie11-eb24cb6d9920, it works fine for me now on IE as well.
> > 
> > 
> > Is the ngx-ssrs-reportviewer is working in the Internet Explorer ? . It is not working for me
> 
> Yes it works for me fine on IE11.

If you don't mind ,Could  you please provide me steps to work in IE 11

**Comment by hmukundappa** [comment]
> > > > > Could you please provide the solution to show the SSRS in Internet Explorer
> > > > 
> > > > 
> > > > I installed all the recommended imports in the polyfill.ts and also in the tsconfig changed the lib to es2018
> > > > "lib": [
> > > > "es2018",
> > > > "dom"
> > > > ]
> > > > Link helped me, https://medium.com/better-programming/how-to-fix-your-angular-app-when-its-not-working-in-ie11-eb24cb6d9920, it works fine for me now on IE as well.
> > > 
> > > 
> > > Is the ngx-ssrs-reportviewer is working in the Internet Explorer ? . It is not working for me
> > 
> > 
> > Yes it works for me fine on IE11.
> 
> If you don't mind ,Could you please provide me steps to work in IE 11

The steps are there in the link I have shared, under the section "Missing Polyfills for Legacy Browsers (IE11)"..Have you done all those installs? 
what is the error you get? add some screen shots or details around issue you are facing.

**Comment by karthiktanj** [comment]
> > > > > > Could you please provide the solution to show the SSRS in Internet Explorer
> > > > > 
> > > > > 
> > > > > I installed all the recommended imports in the polyfill.ts and also in the tsconfig changed the lib to es2018
> > > > > "lib": [
> > > > > "es2018",
> > > > > "dom"
> > > > > ]
> > > > > Link helped me, https://medium.com/better-programming/how-to-fix-your-angular-app-when-its-not-working-in-ie11-eb24cb6d9920, it works fine for me now on IE as well.
> > > > 
> > > > 
> > > > Is the ngx-ssrs-reportviewer is working in the Internet Explorer ? . It is not working for me
> > > 
> > > 
> > > Yes it works for me fine on IE11.
> > 
> > 
> > If you don't mind ,Could you please provide me steps to work in IE 11
> 
> The steps are there in the link I have shared, under the section "Missing Polyfills for Legacy Browsers (IE11)"..Have you done all those installs?
> what is the error you get? add some screen shots or details around issue you are facing.
First time when we run the application blank page is Showing. After refreshing the same page we are the error CustomElem is undefing. PFA of Screenshot
![image](https://user-images.githubusercontent.com/60930903/81817775-ca28a000-954a-11ea-8728-c578990cea0c.png)

**Comment by hmukundappa** [comment]
> > > > > > > Could you please provide the solution to show the SSRS in Internet Explorer
> > > > > > 
> > > > > > 
> > > > > > I installed all the recommended imports in the polyfill.ts and also in the tsconfig changed the lib to es2018
> > > > > > "lib": [
> > > > > > "es2018",
> > > > > > "dom"
> > > > > > ]
> > > > > > Link helped me, https://medium.com/better-programming/how-to-fix-your-angular-app-when-its-not-working-in-ie11-eb24cb6d9920, it works fine for me now on IE as well.
> > > > > 
> > > > > 
> > > > > Is the ngx-ssrs-reportviewer is working in the Internet Explorer ? . It is not working for me
> > > > 
> > > > 
> > > > Yes it works for me fine on IE11.
> > > 
> > > 
> > > If you don't mind ,Could you please provide me steps to work in IE 11
> > 
> > 
> > The steps are there in the link I have shared, under the section "Missing Polyfills for Legacy Browsers (IE11)"..Have you done all those installs?
> > what is the error you get? add some screen shots or details around issue you are facing.
> > First time when we run the application blank page is Showing. After refreshing the same page we are the error CustomElem is undefing. PFA of Screenshot
> > ![image](https://user-images.githubusercontent.com/60930903/81817775-ca28a000-954a-11ea-8728-c578990cea0c.png)

I had the same issue, I just did 2 changes as mentioned in the doc, I have these screenshot of polyfill.ts and tsconfig screen grab, this worked for me, hope this helps..

<img width="239" alt="tsconfigjson" src="https://user-images.githubusercontent.com/28708356/81818793-65f3e500-9526-11ea-9ce4-7573bf7d6fd6.png">
<img width="460" alt="polyfills" src="https://user-images.githubusercontent.com/28708356/81818812-6b512f80-9526-11ea-8b81-c23d4ba0858a.png">

**Comment by karthiktanj** [comment]
> > > > > > > > Could you please provide the solution to show the SSRS in Internet Explorer
> > > > > > > 
> > > > > > > 
> > > > > > > I installed all the recommended imports in the polyfill.ts and also in the tsconfig changed the lib to es2018
> > > > > > > "lib": [
> > > > > > > "es2018",
> > > > > > > "dom"
> > > > > > > ]
> > > > > > > Link helped me, https://medium.com/better-programming/how-to-fix-your-angular-app-when-its-not-working-in-ie11-eb24cb6d9920, it works fine for me now on IE as well.
> > > > > > 
> > > > > > 
> > > > > > Is the ngx-ssrs-reportviewer is working in the Internet Explorer ? . It is not working for me
> > > > > 
> > > > > 
> > > > > Yes it works for me fine on IE11.
> > > > 
> > > > 
> > > > If you don't mind ,Could you please provide me steps to work in IE 11
> > > 
> > > 
> > > The steps are there in the link I have shared, under the section "Missing Polyfills for Legacy Browsers (IE11)"..Have you done all those installs?
> > > what is the error you get? add some screen shots or details around issue you are facing.
> > > First time when we run the application blank page is Showing. After refreshing the same page we are the error CustomElem is undefing. PFA of Screenshot
> > > ![image](https://user-images.githubusercontent.com/60930903/81817775-ca28a000-954a-11ea-8728-c578990cea0c.png)
> 
> I had the same issue, I just did 2 changes as mentioned in the doc, I have these screenshot of polyfill.ts and tsconfig screen grab, this worked for me, hope this helps..
> 
> <img alt="tsconfigjson" width="239" src="https://user-images.githubusercontent.com/28708356/81818793-65f3e500-9526-11ea-9ce4-7573bf7d6fd6.png">
> 
> <img alt="polyfills" width="460" src="https://user-images.githubusercontent.com/28708356/81818812-6b512f80-9526-11ea-8b81-c23d4ba0858a.png">
I am facing the below issue . Cant resolve 
![image](https://user-images.githubusercontent.com/60930903/81824712-6bb3ef80-9553-11ea-8592-27c1493dbc3c.png)

**Comment by tycomo** [comment]
Marking as resolved with @karthiktanj  comments.  Let me know if running into issues with IE11 in latest version and I can add specifics to the docs.  😄
