### ISSUE TITLE
Error in Version 8 

### ISSUE THREAD

**Issue by acajamarca** [tycomo/ngx-ssrs-reportviewer#24]
I am working with angular version 8 and it emits an error when the project is compiled.

ERROR in ./node_modules/ngx-ssrs-reportviewer/fesm2015/ngx-ssrs-reportviewer.js
Module not found: Error: Can't resolve '@angular/elements' in 'C:\XXXXX\FUNC-668\SOLUCIONAPP\FRONTEND\XXXX.XXXX.Web.Pagos\node_modules\ngx-ssrs-reportviewer\fesm2015'.

**Comment by msinghm** [comment]
getting same error

**Comment by fawadtayyab123** [comment]
I'd solved this issue by following #12 on this repository.

**Comment by msinghm** [comment]
> I'd solved this issue by following #12 on this repository.

Thanks So much.

**Comment by tycomo** [comment]
Marking as closed.  Removed need for these dependencies in latest version.
