### ISSUE TITLE
Breaks with Angular 5 :(

### ISSUE THREAD

**Issue by stotty06** [tycomo/ngx-ssrs-reportviewer#3]
Seems to be breaking when upgrading to Angular 5 :(
 
WARNING in ./node_modules/ngx-ssrs-reportviewer/node_modules/@angular/core/@angular/core.es5.js
5659:15-36 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (C:\Dev\ReportServerClient\mat-sidenav-menu-master\node_modules\webpack\lib\dependencies\ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (C:\Dev\ReportServerClient\mat-sidenav-menu-master\node_modules\webpack\lib\Compilation.js:703:24)
    at Compilation.finish (C:\Dev\ReportServerClient\mat-sidenav-menu-master\node_modules\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (C:\Dev\ReportServerClient\mat-sidenav-menu-master\node_modules\webpack\lib\Compiler.js:506:17)
    at C:\Dev\ReportServerClient\mat-sidenav-menu-master\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (C:\Dev\ReportServerClient\mat-sidenav-menu-master\node_modules\webpack\lib\Compilation.js:507:11)
    at processModuleDependencies.err (C:\Dev\ReportServerClient\mat-sidenav-menu-master\node_modules\webpack\lib\Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ ./node_modules/ngx-ssrs-reportviewer/node_modules/@angular/core/@angular/core.es5.js
 @ ./node_modules/ngx-ssrs-reportviewer/ngx-ssrs-reportviewer/ngx-ssrs-reportviewer.es5.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

WARNING in ./node_modules/ngx-ssrs-reportviewer/node_modules/@angular/core/@angular/core.es5.js
5675:15-102 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (C:\Dev\ReportServerClient\mat-sidenav-menu-master\node_modules\webpack\lib\dependencies\ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (C:\Dev\ReportServerClient\mat-sidenav-menu-master\node_modules\webpack\lib\Compilation.js:703:24)
    at Compilation.finish (C:\Dev\ReportServerClient\mat-sidenav-menu-master\node_modules\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (C:\Dev\ReportServerClient\mat-sidenav-menu-master\node_modules\webpack\lib\Compiler.js:506:17)
    at C:\Dev\ReportServerClient\mat-sidenav-menu-master\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (C:\Dev\ReportServerClient\mat-sidenav-menu-master\node_modules\webpack\lib\Compilation.js:507:11)
    at processModuleDependencies.err (C:\Dev\ReportServerClient\mat-sidenav-menu-master\node_modules\webpack\lib\Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ ./node_modules/ngx-ssrs-reportviewer/node_modules/@angular/core/@angular/core.es5.js
 @ ./node_modules/ngx-ssrs-reportviewer/ngx-ssrs-reportviewer/ngx-ssrs-reportviewer.es5.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

Thanks

**Comment by stotty06** [comment]
Fixed this by updating the Angular version for ngx-ssrs-reportviewer.

**Comment by stotty06** [comment]
Now shows in the browser debug, again with Angular 5 only.

ERROR Error: StaticInjectorError[DomSanitizer]: 
  StaticInjectorError[DomSanitizer]: 
    NullInjectorError: No provider for DomSanitizer!

**Comment by ghost** [comment]
having the same problem.  do you know if there is a resolution?

**Comment by pilz97** [comment]
Same Problem..
Does anyone have a solution?

**Comment by marmeek** [comment]
Seems this is not longer active package; Above all package does not work with Angular 6 or 5.

**Comment by nag405** [comment]
im also facing this issue. 
WARNING in ./node_modules/ngx-ssrs-reportviewer/node_modules/@angular/core/@angular/core.es5.js 5659:15-36
Critical dependency: the request of a dependency is an expression

is there any chance to upgrade this module to angular 6 version

**Comment by marmeek** [comment]
No Reply in last 15 days. I guess the developer have muted the notification in this Thread.

**Comment by rogerio-andrade-massaro** [comment]
> im also facing this issue.
> WARNING in ./node_modules/ngx-ssrs-reportviewer/node_modules/@angular/core/@angular/core.es5.js 5659:15-36
> Critical dependency: the request of a dependency is an expression
> 
> is there any chance to upgrade this module to angular 6 version

Hi mate, I had this problem and get the version in https://github.com/tycomo/ngx-ssrs-reportviewer/blob/master/src/app/app.module.ts

it gets the module from another path: import { SSRSReportViewerModule } from './modules/reportviewer/reportviewer.module';

**Comment by marmeek** [comment]
> > im also facing this issue.
> > WARNING in ./node_modules/ngx-ssrs-reportviewer/node_modules/@angular/core/@angular/core.es5.js 5659:15-36
> > Critical dependency: the request of a dependency is an expression
> > is there any chance to upgrade this module to angular 6 version
> 
> Hi mate, I had this problem and get the version in https://github.com/tycomo/ngx-ssrs-reportviewer/blob/master/src/app/app.module.ts
> 
> it gets the module from another path: import { SSRSReportViewerModule } from './modules/reportviewer/reportviewer.module';

After upgrade this will give errors only, nothing works, I invested 3 days in this but was not able to make it even partially working.

**Comment by acacostadeveloper** [comment]
> > > im also facing this issue.
> > > WARNING in ./node_modules/ngx-ssrs-reportviewer/node_modules/@angular/core/@angular/core.es5.js 5659:15-36
> > > Critical dependency: the request of a dependency is an expression
> > > is there any chance to upgrade this module to angular 6 version
> > 
> > 
> > Hi mate, I had this problem and get the version in https://github.com/tycomo/ngx-ssrs-reportviewer/blob/master/src/app/app.module.ts
> > it gets the module from another path: import { SSRSReportViewerModule } from './modules/reportviewer/reportviewer.module';
> 
> After upgrade this will give errors only, nothing works, I invested 3 days in this but was not able to make it even partially working.

Weird, I am with a angular 6 project and it is working well ... Did you get the project in github ? ( https://github.com/tycomo/ngx-ssrs-reportviewer/blob/master/src/app/app.module.ts), try to download it, npm install and try to run ... after that try to copy and paste the code to your project .. good luck and if I can help you just send a message ...

**Comment by pilz97** [comment]
I took a look at the code..
It's very simple what the plugin do!

Example:
Your Reportserver url is http://localhost:8080/ReportServer
The Path of your Report you want to render is http://localhost:8080/ReportServer/Test
And the name of the Report is ExampleReport, with Params: "CustomText", "Date" 

With this information you can easyly render the report, with the following url

http://localhost:8080/ReportServer?/ExampleReport&rs:Embed=true&CustomText=testText&Username=user&Date=05.10.2018

You can also create a PDF or show the renderd report in a pdf viewer, you just have to use the same url with "rs:Format=PDF". 
So with: 
http://localhost:8080/ReportServer?/ExampleReport&rs:Embed=true&CustomText=testText&Username=user&Date=05.10.2018&rs:Format=PDF you will get a PDF (you can use this url in a PDF viewer). (https://docs.microsoft.com/en-us/sql/reporting-services/export-a-report-using-url-access?view=sql-server-2017)


I think with this information you don't need the plugin anymore.

**Comment by tycomo** [comment]
Hi all, unfortunately other obligations have kept me from keeping this up to date.

I have a branch I am working on that will update it to the latest version of Angular that should be out this weekend with improved support and features for SSRS reports in Angular.

Thanks for understanding.

**Comment by rajuvr07** [comment]
Any update on this issue

**Comment by rcanpahali** [comment]
Yeah please, fix this issue.
