### ISSUE TITLE
Integrating Custom security

### ISSUE THREAD

**Issue by raju4886** [tycomo/ngx-ssrs-reportviewer#32]
Hi,
I had implemented forms authentication, for ssrs reports. I'm able to achieve my functionality if i open the report server in a new page/tab.
The same is not able to achieve as expected.
I had modified the reportServer and reportParam. 
ex. reportServer: serverUrl+login.aspx
reportUrl: token(passing a token)
Not able to get the query parameters.
somehow I was able to get my token and validated the user.
when I'm redirecting to report viewer , I'm facing issues.

Can anybody help me out on this?

Thanks,
Raju

**Comment by tycomo** [comment]
duplicate #14 

I will try and get some better documentation up on how to handle this and the options available!!!

**Comment by ahmetb5** [comment]
Hi,

I that possible to use nodejs 'mssql-ssrs' for authentication?

Ex:
var auth = {
  username: 'userName',
  password: 'password',
  workstation: '', // optional
  domain: '' // optional
};
var report = await ssrs.reportExecution.getReportByUrl(reportPath, fileType, parameters, auth)
