### ISSUE TITLE
Update Angular Dependencies (Angular V11)

### ISSUE THREAD

**Issue by danisss9** [tycomo/ngx-ssrs-reportviewer#35]
When running this on Angular V11 app it gives a Depedency warning:

![image](https://user-images.githubusercontent.com/36733433/103568988-6fb7c780-4ebe-11eb-9b20-920be37c7a01.png)

You could update the package.json to support both angular versions. It seems to run fine in Angular 11.
```JSON
    "@angular/animations": "~10.0.6 || ~11.0.0",
    "@angular/common": "~10.0.6 || ~11.0.0",
    "@angular/compiler": "~10.0.6 || ~11.0.0",
    "@angular/core": "~10.0.6 || ~11.0.0",
    "@angular/forms": "~10.0.6 || ~11.0.0",
    "@angular/platform-browser": "~10.0.6 || ~11.0.0",
    "@angular/platform-browser-dynamic": "~10.0.6 || ~11.0.0",
    "@angular/router": "~10.0.6 || ~11.0.0",
```

**Comment by SergioFM98** [comment]
hey you made it work on angular11?

**Comment by danisss9** [comment]
@SergioFM98 It seems to work so far in Angular 11 and 12 if you "npm install --force"
