### ISSUE TITLE
Function calls are not supported in decorators in 'NgModule'

### ISSUE THREAD

**Issue by dgetts192** [tycomo/ngx-ssrs-reportviewer#6]
### Angular Versions

Angular CLI: 1.6.3
Node: 8.3.0
OS: win32 x64
Angular: 5.2.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

angular/cli: 1.6.3
angular-devkit/build-optimizer: 0.0.38
angular-devkit/core: 0.0.25
angular-devkit/schematics: 0.0.48
ngtools/json-schema: 1.1.0
ngtools/webpack: 1.9.3
schematics/angular: 0.1.13
schematics/schematics: 0.0.13
typescript: 2.4.2
webpack: 3.10.0

### The Issue

I am trying to use this package in a large project with lazily loaded modules. I'm not too sure what the cause of the issue is but when I try to import the SSRSReportViewerModule in any module in my app I get the error shown below.

![image](https://user-images.githubusercontent.com/6369686/38494437-cfd34a40-3bed-11e8-81f2-3c804bba48e3.png)

Is there anything I can do to get this to work? Or are some code changes required?

**Comment by JonDosmann** [comment]
I have the same issue. Did you ever resolve it?

**Comment by beinguam** [comment]
I am having the same issue too. Any resolution?

**Comment by celvin** [comment]
same here, is there any other library? is this one becoming unsupported?

**Comment by tycomo** [comment]
Hi @JonDosmann  @celvin  @beinguam , other obligations have kept me from keeping this up to date.

I have a branch I am working on that will update it to the latest version of Angular that should be out this weekend.  This should fix these issues and introduce improved features and tooling.

Thanks for understanding.
