### ISSUE TITLE
It's not working with Angular 5

### ISSUE THREAD

**Issue by naru-shankar** [tycomo/ngx-ssrs-reportviewer#7]
I get below error when I run the applicaiton:
------------------
Unhandled Promise rejection: Template parse errors:
Can't bind to 'reportserver' since it isn't a known property of 'ssrs-reportviewer'.
1. If 'ssrs-reportviewer' is an Angular component and it has 'reportserver' input, then verify that it is part of this module.
2. If 'ssrs-reportviewer' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
    </div>
    <div>
        <ssrs-reportviewer [ERROR ->][reportserver]="reportServer"
                           [reporturl]="reportUrl">
        </ssrs-re"): 
------------------------

**Comment by tycomo** [comment]
Hi @naru-shankar , other obligations have kept me from keeping this up to date.

I have a branch I am working on that will update it to the latest version of Angular that should be out this weekend.

Thanks for understanding.
