### ISSUE TITLE
not work with @angular/core": "^6.0.3

### ISSUE THREAD

**Issue by ghost** [tycomo/ngx-ssrs-reportviewer#8]

**Comment by tycomo** [comment]
Hi @marcodevecchi , other obligations have kept me from keeping this up to date.

I have a branch I am working on that will update it to the latest version of Angular that should be out this weekend.

Thanks for understanding.

**Comment by yasiryc** [comment]
Any update on this? We are currently on Angular 7.2.7 and getting an error when trying to use this package.

**Comment by tycomo** [comment]
Thanks for the response @yasiryc. I have a branch that is almost complete in updating it to the latest version of Angular.  There are just a few small things to fix (making it more customizable, better integration in to the page itself that should be added in this update).  Keep posted in the next few days!

**Comment by acajamarca** [comment]
I am working with angular version 8 and it emits an error when the project is compiled. 

ERROR in ./node_modules/ngx-ssrs-reportviewer/fesm2015/ngx-ssrs-reportviewer.js
Module not found: Error: Can't resolve '@angular/elements' in 'C:\XXXXX\FUNC-668\SOLUCIONAPP\FRONTEND\XXXX.XXXX.Web.Pagos\node_modules\ngx-ssrs-reportviewer\fesm2015'.
