### ISSUE TITLE
ngx-report viewer not loading RDL file

### ISSUE THREAD

**Issue by IDhimmar** [tycomo/ngx-ssrs-reportviewer#9]
![capture](https://user-images.githubusercontent.com/46915757/51515335-46b8dc00-1e39-11e9-91e1-94adb51b6e08.JPG)
I'm new to angular and I'm using **ngx-ssrs-reportviewer** for loading **RDL file(SSRS report)**. But it isn't loading that RDL file and only showing the data of API which I pass at **reportServer** of **app.component.ts** file. My RDL file is in .Net Core API **wwwroot** folder. Could you help me to find out the reason?

Also I set **showparameters** and toolbar to "**true**" still it is not displaying the **parameters** and **toolbar**. Why?

I have attached screenshot for reference. Please send helpful tips.

**Comment by tycomo** [comment]
Right now I do not have support for reading the .rdl and displaying it. Currently it has to be published to the report server for the web app to reach the URL to render it inside the app.

This will be something I investigate as an enhancement.
